### ISSUE TITLE
Need help/advice with QtCharts

### ISSUE THREAD

**Issue by r3d9u11** [filcuc/nimqml#14]
Hi. I have a simple project in QML with one Char and LineSeries:
main.qml
```
import QtQuick 2.2
import QtQuick.Window 2.1
import QtQuick.Layouts 1.1
import QtQuick.Controls 1.2

import QtCharts 2.2

ApplicationWindow {
    width: 400
    height: 300
    title: "Hello World"
    Component.onCompleted: visible = true

    ChartView {
        title: "Oscil"
        id: chartView
        antialiasing: true
        anchors.fill: parent
        LineSeries {
            name: "LineSeries"
            useOpenGL: true
        }
    }

    Timer {
        id: refreshTimer
        interval: 1 / 60 * 1000 // 60 Hz
        running: true
        repeat: true
        onTriggered: {
            //chartView.series(0).
            //dataSource.update(chartView.series(0));
        }
    }
}
```
So, can I feel this "LineSeries" directly from Nim?
I must do something like in [this example of C++ code](https://forum.qt.io/post/444795):
```
...
const auto arrLen = std::extent<declype(arrX)>::value;
Q_ASSERT(std::extent<declype(arrY)>::value == arrLen);
/* QXYSeries*  LineSeries; <- in header and created on the heap*/
for(decltype(awrrLen) i=0;i<arrLen;++i)
LineSeries->append(arrX[i],arrY[i]);
...
```
In fact, I need to call method `LineSeries->append(arrX[i],arrY[i]);` directly from Nim.
Is it possible?

Thanks.

**Comment by filcuc** [comment]
@r3d9u11 I futher improved the example by showing you how to add dynamic points 570027c23121a1c965a7e8c7a665b7b6a7347e47

**Comment by r3d9u11** [comment]
@filcuc many thanks, it's very useful!

**Comment by filcuc** [comment]
@r3d9u11 Fixed the issue with table models

**Comment by r3d9u11** [comment]
@filcuc thanks! does library with latest changes available in nimble?

**Comment by filcuc** [comment]
Yes published latest version

Il 03 Mar 2018 5:32 PM, "r3d9u11" <notifications@github.com> ha scritto:
