### ISSUE TITLE
Static compilation

### ISSUE THREAD

**Issue by r3d9u11** [filcuc/nimqml#16]
Hi. Is it possible to build a standalone application? I mean compile nim-application statically with qt-libs and libDOtherSide (and *.qml files)?

**Comment by filcuc** [comment]
No official support right now. But yes it is possible. Keep in mind that
libdotherside is lgpl

Il 03 Mar 2018 5:37 PM, "r3d9u11" <notifications@github.com> ha scritto:

**Comment by r3d9u11** [comment]
@filcuc Well, I always make my software under MIT license and share source code for target user(s). I think it completely compatible with LGPL :)
