### ISSUE TITLE
[Question] Struggling to understand *abstractitemmodel* example: setup and delete

### ISSUE THREAD

**Issue by mantielero** [filcuc/nimqml#26]
I am trying to understand the [abstractitemmodel](https://github.com/filcuc/nimqml/blob/5c42890e5b14b7d84a2345b060d1b54bfb7aed1b/examples/abstractitemmodel) example.

I don't get these [few lines](https://github.com/filcuc/nimqml/blob/5c42890e5b14b7d84a2345b060d1b54bfb7aed1b/examples/abstractitemmodel/mylistmodel.nim#L12-L16). When I look at the [QAbstractListModel subclassing documentation](https://doc.qt.io/qt-5/qabstractlistmodel.html#subclassing) I am not managing to see where those `delete` and `setup` are explained. 

Any help is welcomed. Regards.

**Comment by filcuc** [comment]
Sadly they're needed in order to make inheritance work. 
The `setup` is the corrisponding class constructor.
When creating your own subclass simply call it in your constructor method.
Delete is the same. It should be called during destruction. In nim a simply attach a delete when invoking new
