### ISSUE TITLE
Update to DOtherSide 0.7

### ISSUE THREAD

**Issue by KnorrFG** [filcuc/nimqml#27]
Hey,
I tried to install everything according to your tutorial, and when I wanted to compile the tutorial (with -d:nimDebugDlOpen) I got the following error message: `libDOtherSide.so.0.6: cannot open shared object file: No such file or directory` which is no surprise, because make install gave me the information: 
```
-- Installing: /usr/local/lib/libDOtherSide.so.0.7.0
-- Installing: /usr/local/lib/libDOtherSide.so.0.7
-- Installing: /usr/local/lib/libDOtherSide.so
```
Could you update nimqml to use the latest version?

**Comment by filcuc** [comment]
Yes right now I've not updated nimqml to th latest version of dotherside. Honestly because I would liked to expose Object connections between QObjects created in the Nim. I cannot guarantee a date for when it will be ready. For now you have to build a dotherside 0.6.x release.
