### ISSUE TITLE
Compiling for OSX Catalina

### ISSUE THREAD

**Issue by notchris** [filcuc/nimqml#29]
Hello, I was able to run the examples and compile the libDOtherSide.dylib for Catalina and wanted to share the steps.

**Install deps with homebrew:**
```bash
brew install qt
brew link qt --force
brew install doxygen
```

**Link qt paths:**

```bash
sudo ln -s /usr/local/Cellar/qt/5.15.1/mkspecs /usr/local/mkspecs
sudo ln -s /usr/local/Cellar/qt/5.15.1/plugins /usr/local/plugins
```

**Then you need to make the libDOtherSide.dylib file:**

- Download project from repo: [dotherside](https://github.com/filcuc/dotherside)
- Follow build steps to create dylib

Hope this helps anyone who is also new with this sort of thing.
**Note:** You have to move the generated dylib to '/usr/local/lib/', and may need to rename the file if the version is appended to the name.

**Comment by filcuc** [comment]
Moved this info into a separate wiki page
