### ISSUE TITLE
could not load: DOtherSide.dll

### ISSUE THREAD

**Issue by levovix0** [filcuc/nimqml#30]
OS Windows
I compiled dotherside (tried different compilers), moved the dll to binary dir (also tried C:\Windows\System32 and C:\Window\SysWOW64)

Standard nim's `dynlib.loadLib` returns nil. Seems like the library is located, but it can't load.

How to fix this?

**Comment by filcuc** [comment]
@levovix0 you need to have also all the Qt libraries in your path. See https://wiki.qt.io/Deploy_an_Application_on_Windows

**Comment by filcuc** [comment]
Another options is to use the env variables QT_PLUGIN_PATH and QML2_IMPORT_PATH 
Google about them for further info.

**Comment by levovix0** [comment]
Ok, thanks, it works.
Maybe you should write about it in the doc?
