### ISSUE TITLE
Nim version requirement, 1.4 vs 1.2

### ISSUE THREAD

**Issue by arnetheduck** [filcuc/nimqml#31]
I noticed nim version requirement was bumped to 1.4 recently, was there a specific reason? We're using 1.2 for a number of projects for which nimqml has been really great and are not planning to migrate until later - curious what broke ;)

**Comment by filcuc** [comment]
nothing really i think we can revert it to 1.2

**Comment by filcuc** [comment]
Well i've just noticed that the requirements has not been set in the .nimble file it's only in the README

**Comment by filcuc** [comment]
@arnetheduck can you confirm that? or have you had problems somewhere compiling the library with 1.2?

**Comment by arnetheduck** [comment]
we're using a pre-bump version right now and haven't tried upgrading really, mainly because of what the readme says right now - we don't use nimble.

**Comment by filcuc** [comment]
ok so nothing to worry
