### ISSUE TITLE
Cannot run with arc gc

### ISSUE THREAD

**Issue by ire4ever1190** [filcuc/nimqml#34]
running the basic example with --gc:arc returns this error

```
/home/name/.nimble/pkgs/nimqml-0.9.0/nimqml/private/qobject.nim(159, 6) Error: cannot bind another '=destroy' to: QObject:ObjectType; previous declaration was constructed here implicitly: /home/name/.choosenim/toolchains/nim-#devel/lib/system/arc.nim(212, 15)
```

**Comment by arkanoid87** [comment]
Can confirm on nim 1.6.0 running helloworld example on just compiled DOtherSide

`/home/arkanoid/.nimble/pkgs/nimqml-0.9.0/nimqml/private/qobject.nim(159, 6) Error: cannot bind another '=destroy' to: QObject:ObjectType; previous declaration was constructed here implicitly: /home/arkanoid/.choosenim/toolchains/nim-1.6.0/lib/system/arc.nim(210, 7)`

**Comment by filcuc** [comment]
Thank you for the report i'll look at it this weekend

**Comment by filcuc** [comment]
@arkanoid87  @ire4ever1190  FYI It took me longer than expected but i think now it should work with both arc and orc
