### ISSUE TITLE
LGPL license makes hard to use NimQml in proprietary code for technical reason

### ISSUE THREAD

**Issue by arkanoid87** [filcuc/nimqml#44]
Following forum thread: https://forum.nim-lang.org/t/8816

There's currently no automated way to generate interface (C headers like) of a nim library to dynamically link it with nim projects.
There's also no clear separation between object files containing the LGPL code and the rest of the code.

This makes technically hard to fulfill LGPL requirements when linking with proprietary code.

@filcuc are you willing to help NimQml users to overcome these technical difficulties?

Thank you

**Comment by arkanoid87** [comment]
Thanks you for enabling this.

Are you also considering switching license to avoid writing exceptions for LGPL?

**Comment by filcuc** [comment]
maybe...but i would prefer to simply add the exception

**Comment by Yardanico** [comment]
@filcuc IANAL but I really don't think that adding such an exception to LGPL makes sense - you'll completely change the license by that single exception, and I don't even know if it'll still be valid. I also think it's much easier to just change the license

**Comment by filcuc** [comment]
@Yardanico  0mq have this kind of exception (see https://github.com/zeromq/libzmq/blob/master/COPYING.LESSER) same for wxwidgets

**Comment by filcuc** [comment]
that said i'm not a laywer too and effectively http://wiki.zeromq.org/area:licensing writes that they've intention to move to MPLv2

**Comment by arkanoid87** [comment]
thanks!
