### ISSUE TITLE
documentation: destructors and defer 

### ISSUE THREAD

**Issue by ShalokShalom** [filcuc/nimqml#46]
The documentation shows that we need defer all the time. 

```nim
proc mainProc() =
  var app = newQApplication()
  defer: app.delete()

  var engine = newQQmlApplicationEngine()
  defer: engine.delete()

  var qVar1 = newQVariant(10)
  defer: qVar1.delete()

  var qVar2 = newQVariant("Hello World")
  defer: qVar2.delete()

  var qVar3 = newQVariant(false)
  defer: qVar3.delete()

  var qVar4 = newQVariant(3.5.float)
  defer: qVar4.delete()
```

http://filcuc.github.io/nimqml/

Destructors seem to make that superflous. Is this already implemented and the documentation outdated?

Or is it not implementated yet and are you interested in doing that? 

Thanks

**Comment by filcuc** [comment]
@ShalokShalom orc support has been added time ago but is blocked by https://github.com/nim-lang/Nim/issues/19402

**Comment by ShalokShalom** [comment]
> @ShalokShalom orc support has been added time ago but is blocked by [nim-lang/Nim#19402](https://github.com/nim-lang/Nim/issues/19402)

This was closed and merged at the 27.9

**Comment by filcuc** [comment]
@ShalokShalom  yes we can cleanup the code...but we need also to require a higher compiler version...dunno if i'm willing to do it though

**Comment by ShalokShalom** [comment]
You mean due to the effort?

**Comment by filcuc** [comment]
@ShalokShalom i'm not going to remove the defer until ORC/ARC becomes the default gc. Since it's not we will reconsider this in Nim v2 version
