### ISSUE TITLE
[Not an Issue] Why is ApplicationWindow required?

### ISSUE THREAD

**Issue by PhilippMDoerner** [filcuc/nimqml#47]
Heyho everybody.
First of all, thank you very much for making this package! I am currently working my way through a couple QML tutorials and playing around with it.

I stumbled over something though:
One of my resources I look at are a series of youtube videos from KDAB about QML. There none of the examples require having an ApplicationWindow component that is set to be visible as the outer-most component in the QML file. However, when I replicate their example, I observed that without the ApplicationWindow component, no window opens and nothing renders. Given that none of the KDAB examples make use of the ApplicationWindow component, I have become curious.

Why is the ApplicationWindow component so mandatory when using nimqml?

**Comment by filcuc** [comment]
@PhilippMDoerner probably the KDAB examples use the [QQuickView ](https://doc.qt.io/qt-6/qquickview.html) or https://doc.qt.io/qt-5/qtquick-qmlscene.html. In those cases the loaded qml is directly the content item of the window so you don't have direct control of the window in qml. QQuickView was used in QtQuick1 from QtQuick2 on instead usually the Qt application is instatiate a QQmlApplicationEngine from C++ and also the window is created from .qml using the ApplicationWindow.
